name: Build and push image

on:
  workflow_call:
    inputs:
      clang_version:
        required: true
        type: string
      latest:
        default: false
        type: boolean
      tag:
        type: string
      push:
        default: false
        type: boolean

env:
  TAG: ${{ inputs.tag && inputs.tag || inputs.clang_version }}
  LATEST_TAG: ${{ inputs.latest == true && 'latest' || '' }}

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          ${{ env.LATEST_TAG }}
          ${{ env.TAG }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: CLANG_VERSION=${{ inputs.clang_version }}
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
