name: Build and push image

on:
  workflow_call:
    inputs:
      base_version:
        default: '22.04'
        type: string
      clang_version:
        required: true
        type: string
      tag:
        default: latest
        type: string
      platforms:
        default: linux/amd64,linux/arm64/v8
        type: string
      push:
        default: false
        type: boolean

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print
      run: env | sort

    - name: Print
      run: |
        echo ${{ github.repository.owner }}
        echo ${{ github.event.repository.owner }}
        echo ${{ github.event.repository.owner.id }}
        echo ${{ github.event.repository.owner.login }}

    - name: Create tags
      id: meta
      uses: docker/metadata-action@v5
      env:
        IMAGE: ${{ github.repository.owner }}/clang-format-${{ inputs.clang_version }}
      with:
        images: |
          ${{ env.IMAGE }}
          ghcr.io/${{ env.IMAGE }}
        tags: |
          ${{ inputs.tag }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository.owner }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          BASE_VERSION=${{ inputs.base_version }}
          CLANG_VERSION=${{ inputs.clang_version }}
        context: .
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
