name: Build and push image

on:
  workflow_call:
    inputs:
      clang_version:
        required: true
        type: string
      push:
        default: false
        type: boolean
      latest:
        default: false
        type: boolean

env:
  LATEST_TAG: ${{ inputs.latest == true && 'latest' }}

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          ${{ inputs.clang_version }}
          ${{ env.LATEST_TAG }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        build-args: CLANG_VERSION=${{ inputs.clang_version }}
