name: Build and push image

on:
  workflow_call:
    inputs:
      base_version:
        default: '22.04'
        type: string
      clang_version:
        required: true
        type: string
      platforms:
        default: linux/amd64,linux/arm64/v8
        type: string
      push:
        default: false
        type: boolean
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create tags
      id: meta
      uses: docker/metadata-action@v5
      env:
        IMAGE: ${{ github.event.repository.owner.login }}/clang-format-${{ inputs.clang_version }}
      with:
        images: |
          ${{ env.IMAGE }}
          ghcr.io/${{ env.IMAGE }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern=nightly
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=semver,pattern={{version}}
        labels: |
          org.opencontainers.image.title=Clang Format
          org.opencontainers.image.description=Dockerized clang-format utility
          org.opencontainers.image.vendor=kszonek

    - name: Login to GHCR
      if: inputs.push == true
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Dockerhub
      if: inputs.push == true
      uses: docker/login-action@v3
      with:
        username: ${{ github.event.repository.owner.login }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          BASE_VERSION=${{ inputs.base_version }}
          CLANG_VERSION=${{ inputs.clang_version }}
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
