name: Nightly build

on:
  pull_request:
    branches:
      - master

jobs:
  clang-format-17:
    uses: ./.github/workflows/_build_and_push_image.yml
    with:
      clang_version: 17
      # push: true
      tag: 'nightly'
    secrets: inherit
