name: Nightly build
on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build-and-push:
    name: Nightly
    uses: ./.github/workflows/_build_and_push_all.yml
    with:
      push: true
    secrets: inherit
