name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  all:
    name: CI
    uses: ./.github/workflows/_build_and_push_all.yml
  cleanup:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/delete-package-versions@v4
      with:
        package-name: 'clang-format'
        package-type: 'container'
        min-versions-to-keep: 0
