name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  all:
    name: CI
    uses: ./.github/workflows/_build_and_push_all.yml
  cleanup:
    uses: actions/delete-package-versions@v4
    with:
      package-name: 'clang-format-docker'
      package-type: 'container'
      min-versions-to-keep: 0
