name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  clang-format-7:
    uses: ./.github/workflows/_build_and_push_image.yml
    with:
      base_version: 18.04
      clang_version: 7
      push: true
